server:
  port: 9000
spring:
  profiles:
    active: default
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/amath?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: zhaolin
    password: zhaolin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 3
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  typeAliasesPackage: tech.amath0312.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  offsetAsPageNum: false